spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    password:
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate :
        format_sql: true
       # dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
